name: my-first-workflow
# To get trigger on every push in the repo in any branch
on: push


jobs:
  job1:
     name: JOB1
     runs-on: ubuntu-latest
     steps:
       - name: Running Single command in Job1
         run: echo "Hi this is my first Github workflow"
       - name: Checking OS Relaese for GitHub Hosted Runner
         run: cat /etc/os-release
       - name: Calling Sleep
         run: sleep 10
  job2: 
     name: JOB2
     runs-on: ubuntu-latest
     steps:
       - name: Checking the host name for runner
         run: hostname
       - name: Running multiple commands
         run: |
           echo "Hi I Love Biryani"
           echo "Current Time is Date"
           sleep 10
