name: my-first-workflow
# To get trigger on every push in the repo in any branch
on: push


jobs:
  job1:
     name: JOB1
     runs-on: ubuntu-latest
     steps:
       - name: Running Single command in Job1
         run: echo "Hi this is my first Github workflow"
       - name: Checking OS Relesr for GitHub Hosted Runner
         run: cat /etc/hosted relese
